#!/bin/bash

chunkc=/usr/local/bin/chunkc
spaces=/usr/local/bin/DisplaySpaces

sleep 2.00
mode=$($chunkc tiling::query -d mode)
spacesout=$($spaces)

echo "$mode@${spacesout: -1}@${spacesout: -3:1}@$(sh ./scripts/activeWindow.sh)"
